disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_name

opt_in_rules:
  - empty_count
  - missing_docs

excluded:
  - Pods
  - BetComponents

force_cast: warning
force_try: warning
function_body_length:
  warning: 60
  error: 100

reporter: "xcode"
