name: 2 Down Press
options:
  bundleIdPrefix: com.erikhsu
  deploymentTarget:
    iOS: 16.0
targets:
  2 Down Press:
    type: application
    platform: iOS
    sources:
      - path: Views
      - path: Models
    dependencies:
      - package: BetComponents
        product: BetComponents
packages:
  BetComponents:
    path: BetComponents 